name: release
on:
  release:
    types:
      - published

jobs:
  update_gh_pages:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # need this so tags are pulled and versions work

      - uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: '2.0.2-2' # versions: https://github.com/mamba-org/micromamba-releases
          environment-file: '.github/test_conda_env.yml'
          init-shell: >-
            bash
            powershell
          cache-environment: true
          post-cleanup: 'all'

      # Not sure why this is needed but it appears to be the case
      - name: fix env
        shell: bash -l {0}
        run: |
          micromamba shell init --shell bash --root-prefix=~/micromamba
          eval "$(micromamba shell hook --shell bash)"
          micromamba activate test

      - name: git config
        shell: bash -l {0}
        run: |
          git config --global user.email "donotemailme@example.com"
          git config --global user.name "GithubActions"

      - name: build docs
        shell: bash -l {0}
        run: |
          python scripts/stage_docs.py --remove-dirty

      - name: push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          force: true
          directory: ../obsplus_documentation

  publish_package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # need this so tags are pulled and versions work

      - uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: '2.0.2-2' # versions: https://github.com/mamba-org/micromamba-releases
          environment-file: '.github/test_conda_env.yml'
          init-shell: >-
            bash
            powershell
          cache-environment: true
          post-cleanup: 'all'

      # Not sure why this is needed but it appears to be the case
      - name: fix env
        shell: bash -l {0}
        run: |
          micromamba shell init --shell bash --root-prefix=~/micromamba
          eval "$(micromamba shell hook --shell bash)"
          micromamba activate test

      - name: install obsplus
        shell: bash -l {0}
        run: |
          pip install -e .[dev]

      - name: create dists
        shell: bash -l {0}
        run: |
          python -m pip install build
          python -m build

      - name: publish package to pypi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_TOKEN }}
